### ISSUE TITLE
能支持Footer吗？

### ISSUE THREAD

**Issue by lic2050** [shenzhen2017/compose-refreshlayout#1]

**Comment by RicardoJiang** [comment]
Compose使用Paging可以很方便地实现加载更多footer效果，所以看起来没有必要在这个库里支持footer

**Comment by appdev** [comment]
还是希望能支持Footer，应用场景很多的。

**Comment by RicardoJiang** [comment]
> 还是希望能支持Footer，应用场景很多的。

怎么说？有哪些是Paging不能实现的呢?

**Comment by appdev** [comment]
> > 还是希望能支持Footer，应用场景很多的。
> 
> 怎么说？有哪些是Paging不能实现的呢?

Paging对数据的格式有要求，但是有时候后端返回的数据根本没有 pageNumber 相关的东西

**Comment by zhaichenyang** [comment]
> > 还是希望能支持Footer，应用场景很多的。
> 
> 怎么说？有哪些是Paging不能实现的呢?

请问 Paging + Compose 能实现局部刷新吗？就比如本地的某个操作会导致 item 中的某个状态改变，只刷新这个 item

**Comment by fansangg** [comment]
> > > 还是希望能支持Footer，应用场景很多的。
> > 
> > 
> > 怎么说？有哪些是Paging不能实现的呢?
> 
> Paging对数据的格式有要求，但是有时候后端返回的数据根本没有 pageNumber 相关的东西

可以滑动到底部的时候加一个loading的item，然后做加载第二页的请求
