### ISSUE TITLE
在下拉刷新的时候，list 还能上下滑动

### ISSUE THREAD

**Issue by zhaichenyang** [shenzhen2017/compose-refreshlayout#2]
感觉预期应该是下拉刷新时，禁用 list 的滑动，刷新结束再开始可滑

**Comment by RicardoJiang** [comment]
看了下，SwipeRefreshLayout与SmartRefreshLayout在下拉刷新时都是可以滑动的，这应该是正常现象
如果有需要可以在外部处理，即isRefreshing时禁止LazyColumn滚动，可参考：https://stackoverflow.com/questions/66502096/how-to-disable-and-enable-scrolling-in-lazycolumn-lazyrow-in-jetpack-compose
