### ISSUE TITLE
可以上拉加载更多不

### ISSUE THREAD

**Issue by shizhilya** [shenzhen2017/compose-refreshlayout#3]

**Comment by RicardoJiang** [comment]
因为Paging库支持上拉加载更多，所以这个库没有支持这个功能，可以跟paging结合使用

**Comment by shizhilya** [comment]
嗯嗯 

如果像 [SmartRefreshLayout](https://github.com/scwang90/SmartRefreshLayout) 一样，无需 paging 也可支持上拉 ，应用范围应该更广
